// <auto-generated />
using BlazorPortfolio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorPortfolio.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260928094539_ProjectLinks")]
    partial class ProjectLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorPortfolio.Data.Models.Experience", b =>
                {
                    b.Property<int>("ExperienceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExperienceId"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("EndYear")
                        .HasColumnType("int");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("SoftwareBased")
                        .HasColumnType("bit");

                    b.Property<int>("StartYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ExperienceId");

                    b.ToTable("Experience");

                    b.HasData(
                        new
                        {
                            ExperienceId = 3,
                            Company = "Cucumber",
                            EndYear = 2019,
                            Framework = "jQuery",
                            Languages = "JavaScript, HTML, CSS",
                            SoftwareBased = true,
                            StartYear = 2019,
                            Title = "Developer"
                        },
                        new
                        {
                            ExperienceId = 4,
                            Company = "The Raft",
                            EndYear = 2020,
                            Framework = "N/A",
                            Languages = "N/A",
                            SoftwareBased = false,
                            StartYear = 2016,
                            Title = "Kitchen Hand"
                        },
                        new
                        {
                            ExperienceId = 5,
                            Company = "Bay of Plenty Times",
                            EndYear = 2013,
                            Framework = "N/A",
                            Languages = "N/A",
                            SoftwareBased = false,
                            StartYear = 2009,
                            Title = "Paper Deliverer"
                        },
                        new
                        {
                            ExperienceId = 6,
                            Company = "Radfords",
                            EndYear = 2024,
                            Framework = "Windows Forms, Xamarin, WPF, Blazor, MAUI",
                            Languages = "C#, VB.net, SQL",
                            SoftwareBased = true,
                            StartYear = 2020,
                            Title = "Full Stack Developer"
                        },
                        new
                        {
                            ExperienceId = 7,
                            Company = "Emydex Technology",
                            EndYear = 2026,
                            Framework = "Windows Forms",
                            Languages = "C#, SQL",
                            SoftwareBased = true,
                            StartYear = 2024,
                            Title = "Solution Engineer"
                        });
                });

            modelBuilder.Entity("BlazorPortfolio.Data.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Framework")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GithubLink")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProjectId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectId = 1,
                            Active = true,
                            Description = "Current web portfolio",
                            Framework = "Blazor",
                            GithubLink = "https://github.com/Justiphi/BlazorPortfolio",
                            Languages = "C#",
                            ProjectLink = "https://traviswylie.co.nz",
                            Title = "Blazor Portfolio"
                        },
                        new
                        {
                            ProjectId = 2,
                            Active = false,
                            Description = "Previous web portfolio",
                            Framework = "ASP.net, React",
                            GithubLink = "https://github.com/Justiphi/Travis-CV",
                            Languages = "C#, TypeScript",
                            Title = "Web Portfolio"
                        },
                        new
                        {
                            ProjectId = 3,
                            Active = false,
                            Description = "Discord Bot",
                            Framework = "Dotnet Core",
                            GithubLink = "https://github.com/Justiphi/Tatenashi",
                            Languages = "C#",
                            Title = "Tatenashi"
                        },
                        new
                        {
                            ProjectId = 4,
                            Active = true,
                            Description = "Code for pip boy prop",
                            Framework = "PyGame",
                            GithubLink = "https://github.com/Justiphi/pipboy",
                            Languages = "Python",
                            Title = "Pip Boy"
                        },
                        new
                        {
                            ProjectId = 5,
                            Active = false,
                            Description = "Azure based Voice Assistant (superseded by ADA-MKII)",
                            Framework = "WPF, Avalonia",
                            GithubLink = "https://github.com/Justiphi/Project-RIANTI",
                            Languages = "C#",
                            Title = "Project RIANTI"
                        },
                        new
                        {
                            ProjectId = 6,
                            Active = true,
                            Description = "MTG dice and coin generator used for tutoring programming",
                            Framework = "MAUI",
                            GithubLink = "https://github.com/Justiphi/DiceApp",
                            Languages = "C#",
                            Title = "Dice & Coins"
                        },
                        new
                        {
                            ProjectId = 7,
                            Active = true,
                            Description = "Voice Assistant",
                            Framework = "MAUI",
                            GithubLink = "https://github.com/Justiphi/ADA-MKII",
                            Languages = "C#",
                            Title = "ADA-MKII"
                        },
                        new
                        {
                            ProjectId = 8,
                            Active = false,
                            Description = "Proof of concept Computer Vision application",
                            Framework = "WPF",
                            GithubLink = "https://github.com/Justiphi/peoplecounter",
                            Languages = "C#",
                            Title = "People Counter"
                        },
                        new
                        {
                            ProjectId = 9,
                            Active = true,
                            Description = "Current web portfolio made with react",
                            Framework = "React",
                            GithubLink = "https://github.com/Justiphi/reactportfolio",
                            Languages = "JavaScript",
                            ProjectLink = "https://react.traviswylie.co.nz",
                            Title = "React Portfolio"
                        },
                        new
                        {
                            ProjectId = 10,
                            Active = true,
                            Description = "JustiPhi Technologies website",
                            Framework = "ASP.Net, Angular",
                            GithubLink = "https://github.com/Justiphi/justiphisite",
                            Languages = "C#, TypeScript",
                            ProjectLink = "https://justiphi.co.nz",
                            Title = "JustiPhi Technologies"
                        });
                });

            modelBuilder.Entity("BlazorPortfolio.Data.Models.Qualification", b =>
                {
                    b.Property<int>("QualificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QualificationId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("QualificationId");

                    b.ToTable("Qualifications");

                    b.HasData(
                        new
                        {
                            QualificationId = 1,
                            Location = "Otumoetai College",
                            Title = "NCEA Level 3",
                            Year = 2016
                        },
                        new
                        {
                            QualificationId = 2,
                            Location = "Toi Ohomai",
                            Title = "Diploma in Applied Computing (Level 5 with distinction)",
                            Year = 2017
                        },
                        new
                        {
                            QualificationId = 3,
                            Location = "Toi Ohomai",
                            Title = "Skills for Entrepeneurs (Level 7)",
                            Year = 2018
                        },
                        new
                        {
                            QualificationId = 4,
                            Location = "Toi Ohomai",
                            Title = "Diploma in Software Development (Level 6)",
                            Year = 2018
                        },
                        new
                        {
                            QualificationId = 5,
                            Location = "University of Waikato",
                            Title = "Bachelors of Science, Major in Applied Computing",
                            Year = 2019
                        },
                        new
                        {
                            QualificationId = 6,
                            Location = "EMA+",
                            Title = "Certificate in Health and Safety Representation (Level 3)",
                            Year = 2020
                        },
                        new
                        {
                            QualificationId = 7,
                            Location = "FreeCodeCamp",
                            Title = "Foundational C# with Microsoft",
                            Year = 2024
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
